# Generated by Django 2.0.6 on 2018-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='NYSC_call_up_number',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.TextField(default='University of Ibadan', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='07034366179', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_code_number',
            field=models.CharField(default='12634', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state_of_service',
            field=models.TextField(default='Zamfara', max_length=20),
        ),
    ]
