# Generated by Django 2.0.6 on 2018-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180704_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NYSC_call_up_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staff_code_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_service',
            field=models.CharField(max_length=20),
        ),
    ]
