# Generated by Django 2.0.6 on 2018-07-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180705_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff_code_number',
            new_name='state_code_number',
        ),
    ]
