# Generated by Django 2.0.6 on 2018-07-04 20:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20180702_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
