# Generated by Django 2.0.6 on 2018-07-05 17:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20180704_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
