# Generated by Django 2.0.6 on 2018-06-30 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'landlord',
                'verbose_name_plural': 'landlords',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
